### ISSUE TITLE
Gnews API Leaks

### ISSUE THREAD

**Issue by mirfani340** [mirfani340/climate-aware.id#10]
I have found the security issues that occour on project sir, here are the provided issues:
![image](https://github.com/mirfani340/hackfest-gdsc-kopet-team/assets/73763532/e9b53a6d-2b66-4524-8101-5ecb4d5269a8)

Curl Requests to prove the issues:
![image](https://github.com/mirfani340/hackfest-gdsc-kopet-team/assets/73763532/fd184038-a168-470f-91a7-27ace9071299)

@dimyatimaulana @Mr-buddyy

**Comment by dimyatimaulana** [comment]
What causes this issue?

**Comment by dimyatimaulana** [comment]
You already put the endpoint and key in environment variable right?

**Comment by mirfani340** [comment]
> You already put the endpoint and key in environment variable right?

Yes, i'm still investigate it also, i believe its the API algorithm in code it self
